### ISSUE TITLE
Codebase clean-up roadmap

### ISSUE THREAD

**Issue by AudranTourneur** [c2i-junia/minecraft-rust#118]
As part of the next milestone, the project needs some cleaning.

Build process:
- [ ] Think about Justfile.
- [ ] Dockerize server.
- [ ] Server should be distributed in the releases.

Code:
- [ ] Refactor network API (unify all network calls behind the same abstraction) .
- [ ] Server should correctly save the world, player positions and inventories.
- [ ] Player name should be displayed in-game.
- [ ] Player should be able to pick their name either by providing a CLI flag or in the menu. A popup should appear only the first time since the name should be saved in a dedicated save file in the game folder.
- [ ] Do something about the world inspector so that it doesn't hide the debug information by default.
- [ ] For textures, avoid texture duplication (e.g. for dirt and sand) 

Other : 
- [ ] Investigate auto-generation of documentation
- [ ] Maybe talk about configuring `cargo fmt`
